import { t } from '../data/localization.js';
import { rooms } from '../core/rooms.js';
import { renderRoomDecor } from './scenes.js';
import { getEmotion } from '../core/state.js';
import { renderPet } from './pet.js';
const labels={hunger:'Сытость',thirst:'Жажда',cleanliness:'Чистота',mood:'Настрой',energy:'Энергия',toilet:'Лоток',health:'Здоровье'};
const meter=(k,v)=>`<div class="need-line"><div class="need-label"><span class="need-mark ${k}"></span><span>${labels[k]}</span><strong>${Math.round(v)}</strong></div><div class="meter"><i style="width:${v}%"></i></div></div>`;
export function renderWelcome(lang='ru'){return `<main class="welcome-screen"><div class="brand-mark">CK</div><h1>${t('title',lang)}</h1><p>${t('tagline',lang)}</p><section class="name-card"><label for="pet-name">${t('namePrompt',lang)}</label><input id="pet-name" maxlength="16" autocomplete="off" placeholder="${t('namePlaceholder',lang)}"><button id="start-game" class="primary" disabled>${t('start',lang)}</button></section></main>`;}
export function renderGame(state,bubble='',ui={}){
 const lang=state.settings?.language||'ru',room=rooms[state.room]||rooms.living,food=state.inventory.food||{};
 const actions={kitchen:ui.fridgeOpen?`<div class="fridge-panel open"><div class="fridge-head"><b>Холодильник открыт</b><span>Выбери еду</span></div><div class="food-choice"><button class="food-card" data-action="feed" data-food="dryFood"><span class="food-emoji">🥣</span><b>Корм</b><small>×${food.dryFood||0}</small></button><button class="food-card" data-action="feed" data-food="wetFood"><span class="food-emoji">🥫</span><b>Влажный</b><small>×${food.wetFood||0}</small></button><button class="food-card" data-action="feed" data-food="fishTreat"><span class="food-emoji">🐟</span><b>Рыбка</b><small>×${food.fishTreat||0}</small></button></div></div>`:`<div class="object-tip">Нажми на холодильник</div>`,living:`<div class="object-tip pet-direct-tip">Погладь Luna пальцем</div>`};
 const action=actions[state.room]||'';
 const nav=[['living','⌂','Холл'],['kitchen','♨','Кухня']];
 return `<main class="game-shell ${room.className} activity-${state.activity?.type||'idle'}">
 <header class="topbar"><div class="identity"><div class="avatar-mini">L</div><div><b>${state.name}</b><small>Lv. ${state.economy.level} · ${state.economy.xp}/250 XP</small></div></div><div class="currency"><span class="coin-dot"></span><b>${state.economy.coins}</b></div><button class="icon-button sound-button" data-action="sound" aria-label="Музыка">♫</button><button class="icon-button" data-action="settings" aria-label="Настройки">⚙</button></header>
 <section class="mini-needs"><div><b>♥</b><strong>${Math.round(state.needs.happiness)}%</strong><small>Счастье</small></div><div><b>●</b><strong>${Math.round(state.needs.hunger)}%</strong><small>Сытость</small></div><div><b>◆</b><strong>${Math.round(state.needs.thirst)}%</strong><small>Вода</small></div><div><b>☾</b><strong>${Math.round(state.needs.energy)}%</strong><small>Энергия</small></div></section>
 <section class="scene"><aside class="side-nav">${nav.map(([id,ico,label])=>`<button data-room="${id}" class="${state.room===id?'active':''}"><b>${ico}</b><small>${label}</small></button>`).join('')}</aside><div class="room-title">${t(room.labelKey,lang)}</div>${renderRoomDecor(state.room,{...ui,lampOn:state.bedroom?.lampOn!==false})}<div class="scene-light"></div><button class="pet-button" data-action="pet" aria-label="Погладить Luna">${renderPet({sleeping:state.sleeping,emotion:getEmotion(state),activity:state.activity?.type||'idle'})}</button>${bubble?`<div class="speech-bubble">${bubble}</div>`:''}<div class="pet-name">${state.name}</div>${action}<div class="primary-actions"><button data-room="kitchen">🥣<span>Покормить</span></button><button data-action="drink">💧<span>Дать воду</span></button><button data-action="pet">💜<span>Играть</span></button></div></section>
 </main>`;
}