import { t } from '../data/localization.js';
import { rooms } from '../core/rooms.js';
import { renderRoomDecor } from './scenes.js';
import { getEmotion } from '../core/state.js';
import { renderPet } from './pet.js';
import { catalog,categories } from '../core/shop.js';
import { quests,achievements,levelData } from '../core/progression.js';
const labels={hunger:'Сытость',thirst:'Жажда',cleanliness:'Чистота',mood:'Настрой',energy:'Энергия',toilet:'Лоток',health:'Здоровье'};
const meter=(k,v)=>`<div class="need-line"><div class="need-label"><span class="need-mark ${k}"></span><span>${labels[k]}</span><strong>${Math.round(v)}</strong></div><div class="meter"><i style="width:${v}%"></i></div></div>`;
export function renderWelcome(lang='ru'){return `<main class="welcome-screen"><div class="brand-mark">CK</div><h1>${t('title',lang)}</h1><p>${t('tagline',lang)}</p><section class="name-card"><label for="pet-name">${t('namePrompt',lang)}</label><input id="pet-name" maxlength="16" autocomplete="off" placeholder="${t('namePlaceholder',lang)}"><button id="start-game" class="primary" disabled>${t('start',lang)}</button></section></main>`;}
function shopPanel(state){const owned=state.inventory.owned||[];return `<div class="game-panel shop-panel"><div class="panel-head"><b>Магазин</b><button data-close-panel>×</button></div><div class="catalog-grid">${catalog.map(i=>`<button data-buy="${i.id}" ${state.economy.level<i.level?'disabled':''}><b>${i.name}</b><small>${i.price} 🪙 · ${i.rarity}${owned.includes(i.id)&&i.category!=='food'?' · ✓':''}</small></button>`).join('')}</div></div>`}
function wardrobePanel(state){const ids=state.inventory.clothes||[];return `<div class="game-panel"><div class="panel-head"><b>Гардероб</b><button data-close-panel>×</button></div><div class="catalog-grid">${ids.length?ids.map(id=>{const i=catalog.find(x=>x.id===id);return i?`<button data-equip="${id}"><b>${i.name}</b><small>Надеть</small></button>`:''}).join(''):'<p>Одежду можно купить в магазине.</p>'}</div></div>`}
function progressPanel(state){const p=state.progress||{actions:{},claimed:[],achievements:[],streak:0};return `<div class="game-panel"><div class="panel-head"><b>Награды · серия ${p.streak||0}</b><button data-close-panel>×</button></div><button class="reward-button" data-daily>Ежедневный подарок</button>${quests.map(q=>`<button class="reward-button" data-quest="${q.id}">${q.name}: ${p.actions?.[q.type]||0}/${q.goal} · ${q.reward}🪙 ${p.claimed?.includes(q.id)?'✓':''}</button>`).join('')}<div class="achievement-list">${achievements.map(a=>`<span>${p.achievements?.includes(a.id)?'✓':'○'} ${a.name}</span>`).join('')}</div></div>`}
function settingsPanel(state){const s=state.settings||{};return `<div class="settings-panel"><div class="panel-head"><b>Настройки</b><button data-action="settings">×</button></div>
<label class="toggle">Музыка <input data-setting="musicEnabled" type="checkbox" ${s.musicEnabled!==false?'checked':''}></label><label>Громкость <input data-setting="musicVolume" type="range" min="0" max="1" step=".05" value="${s.musicVolume??.35}"></label>
<label class="toggle">Звуки <input data-setting="sfxEnabled" type="checkbox" ${s.sfxEnabled!==false?'checked':''}></label><label>Громкость <input data-setting="sfxVolume" type="range" min="0" max="1" step=".05" value="${s.sfxVolume??.7}"></label>
<label class="toggle">Голос Luna <input data-setting="voiceEnabled" type="checkbox" ${s.voiceEnabled!==false?'checked':''}></label><label>Громкость <input data-setting="voiceVolume" type="range" min="0" max="1" step=".05" value="${s.voiceVolume??.65}"></label>
<label>Язык <select data-setting="language"><option value="ru" ${s.language==='ru'?'selected':''}>Русский</option><option value="uk" ${s.language==='uk'?'selected':''}>Українська</option><option value="en" ${s.language==='en'?'selected':''}>English</option></select></label>
<label class="toggle">Субтитры <input data-setting="subtitles" type="checkbox" ${s.subtitles!==false?'checked':''}></label>
<label class="toggle">Меньше движения <input data-setting="reduceMotion" type="checkbox" ${s.reduceMotion?'checked':''}></label>
<label class="toggle">Вибрация <input data-setting="haptics" type="checkbox" ${s.haptics!==false?'checked':''}></label>
<label>Графика <select data-setting="graphics"><option value="high" ${s.graphics==='high'?'selected':''}>Высокая</option><option value="balanced" ${s.graphics==='balanced'?'selected':''}>Баланс</option><option value="low" ${s.graphics==='low'?'selected':''}>Экономия</option></select></label>
<label class="toggle">Энергосбережение <input data-setting="batterySaver" type="checkbox" ${s.batterySaver?'checked':''}></label>
<label class="toggle">Уведомления <input data-setting="notifications" type="checkbox" ${s.notifications?'checked':''}></label>
<label class="toggle">Подтверждать покупки <input data-setting="purchaseConfirm" type="checkbox" ${s.purchaseConfirm!==false?'checked':''}></label>
<div class="settings-links"><button data-action="help">Помощь</button><button data-action="support">Поддержка</button></div></div>`}
export function renderGame(state,bubble='',ui={}){
 const lang=state.settings?.language||'ru',room=rooms[state.room]||rooms.living,food=state.inventory.food||{};
 const actions={kitchen:ui.fridgeOpen?`<div class="fridge-panel open"><div class="fridge-head"><b>Холодильник</b><button class="fridge-close" data-action="open-fridge" aria-label="Закрыть">×</button></div><div class="food-choice"><button class="food-card" data-action="feed" data-food="dryFood"><span class="food-emoji">🥣</span><b>Корм</b><small>×${food.dryFood||0}</small></button><button class="food-card" data-action="feed" data-food="wetFood"><span class="food-emoji">🥫</span><b>Влажный</b><small>×${food.wetFood||0}</small></button><button class="food-card" data-action="feed" data-food="fishTreat"><span class="food-emoji">🐟</span><b>Рыбка</b><small>×${food.fishTreat||0}</small></button></div></div>`:''};
 const action=(actions[state.room]||'')+(ui.settingsOpen?settingsPanel(state):'')+(ui.panel==='shop'?shopPanel(state):'')+(ui.panel==='wardrobe'?wardrobePanel(state):'')+(ui.panel==='progress'?progressPanel(state):'');
 const nav=[['living','🏠','Холл'],['kitchen','🍽️','Кухня'],['bedroom','🌙','Спальня'],['bathroom','🛁','Ванная'],['toilet','🚽','Туалет'],['wardrobe','👗','Гардероб'],['playroom','🧶','Игры'],['store','🛍️','Магазин'],['lake','🎣','Озеро']];
 return `<main class="game-shell ${room.className} activity-${state.activity?.type||'idle'} ${state.settings?.reduceMotion?'reduce-motion':''}">
 <header class="topbar"><div class="identity"><div class="avatar-mini">L</div><div><b>${state.name}</b><small>Lv. ${state.economy.level} · ${state.economy.xp}/250 XP</small></div></div><div class="currency"><span class="coin-dot"></span><b>${state.economy.coins}</b></div><button class="icon-button" data-action="progress" aria-label="Награды">★</button><button class="icon-button sound-button" data-action="sound" aria-label="Музыка">♫</button><button class="icon-button" data-action="settings" aria-label="Настройки">⚙</button></header>
 <section class="mini-needs"><div><b>♥</b><strong>${Math.round(state.needs.happiness)}%</strong><small>Счастье</small></div><div><b>●</b><strong>${Math.round(state.needs.hunger)}%</strong><small>Сытость</small></div><div><b>◆</b><strong>${Math.round(state.needs.thirst)}%</strong><small>Вода</small></div><div><b>☾</b><strong>${Math.round(state.needs.energy)}%</strong><small>Энергия</small></div></section>
 <section class="scene"><aside class="side-nav">${nav.map(([id,ico,label])=>`<button data-room="${id}" class="${state.room===id?'active':''}"><b>${ico}</b><small>${label}</small></button>`).join('')}</aside>${renderRoomDecor(state.room,{...ui,lampOn:state.bedroom?.lampOn!==false})}<button class="pet-button" data-action="pet" aria-label="Погладить Luna">${renderPet({sleeping:state.sleeping,emotion:getEmotion(state),activity:state.activity?.type||'idle',movement:state.movement})}</button>${bubble?`<div class="speech-bubble">${bubble}</div>`:''}${action}</section>
 </main>`;
}