import { HALL_BG } from '../data/roomAssets.js';
export function renderRoomDecor(room,ui={}){
 const common='<div class="floor-glow"></div>';
 if(room==='kitchen')return `<div class="decor kitchen-decor">${common}<div class="cabinet left"></div><div class="cabinet right"></div><button class="scene-object fridge-object ${ui.fridgeOpen?'open':''}" data-object="fridge" aria-label="Открыть холодильник"><span class="fridge-door"><i class="fridge-handle"></i></span><span class="fridge-inside"><i>🥛</i><i>🐟</i><i>🍗</i></span></button><div class="counter"><button class="scene-object bowl-object" data-object="bowl" aria-label="Миска"><span class="bowl"></span></button></div></div>`;
 if(room==='bedroom')return `<div class="decor bedroom-decor ${ui.lampOn===false?'lamp-off':''}">${common}<button class="scene-object lamp-object" data-object="lamp" aria-label="Лампа"><span class="wall-lamp"><i></i></span></button><button class="scene-object bed-object" data-object="bed" aria-label="Кровать"><span class="bed"><i class="pillow"></i><i class="blanket"></i></span></button><div class="nightstand"></div></div>`;
 if(room==='bathroom')return `<div class="decor bathroom-decor">${common}<button class="scene-object tub-object" data-object="tub" aria-label="Ванна"><span class="tub"></span><span class="foam">○ ◌ ○</span></button><div class="shower"></div><div class="bath-shelf"></div></div>`;
 if(room==='toilet')return `<div class="decor toilet-decor">${common}<button class="scene-object litter-object" data-object="litter" aria-label="Лоток"><span class="litter-box"></span></button><div class="bath-shelf"></div></div>`;
 if(room==='wardrobe')return `<div class="decor wardrobe-decor">${common}<button class="scene-object closet-object" data-object="closet" aria-label="Гардероб"><span class="closet"></span></button><div class="mirror"></div></div>`;
 if(room==='playroom')return `<div class="decor playroom-decor">${common}<button class="scene-object toy-object" data-object="toy" aria-label="Игрушки"><span class="toy-box">🧶</span></button><div class="play-rug"></div><div class="cat-tree"></div></div>`;
 if(room==='lake')return `<div class="decor lake-decor"><div class="sky"></div><div class="hills"></div><button class="scene-object water-object" data-object="water" aria-label="Рыбачить"><span class="water"></span></button><div class="dock"></div></div>`;
 return `<div class="decor living-decor real-room"><img class="room-background" src="${HALL_BG}" alt="" draggable="false"><div class="room-vignette"></div><button class="scene-hotspot hall-toy-hotspot" data-object="toy" aria-label="Игрушки"></button><button class="scene-hotspot hall-kitchen-hotspot" data-room="kitchen" aria-label="Кухня"></button></div>`;
}