import { HALL_BG, ROOM_BACKGROUNDS } from '../data/roomAssets.js';
export function renderRoomDecor(room,ui={}){
 const common='<div class="floor-glow"></div>';
 const bg=ROOM_BACKGROUNDS[room];
 const background=bg?`<img class="room-background" src="${bg}" alt="" draggable="false"><div class="room-vignette"></div>`:'';
 if(room==='kitchen')return `<div class="decor kitchen-decor kitchen-premium real-room">${background}${common}<div class="kitchen-window"><span></span></div><div class="kitchen-wall-light"></div><div class="kitchen-upper u1"></div><div class="kitchen-upper u2"></div><div class="kitchen-counter"><span class="sink"></span><span class="plant-pot"></span></div><div class="kitchen-lower l1"></div><div class="kitchen-lower l2"></div><button class="scene-object fridge-object ${ui.fridgeOpen?'open':''}" data-object="fridge" aria-label="Открыть холодильник"><span class="fridge-inside"><i>🥣</i><i>🥫</i><i>🐟</i></span><span class="fridge-door"><i class="fridge-handle"></i><b class="fridge-note">LUNA ♥</b></span></button><button class="scene-object bowl-object kitchen-bowl" data-object="bowl" aria-label="Миска"><span class="bowl"></span></button><div class="kitchen-rug"></div></div>`;
 if(room==='bedroom')return `<div class="decor bedroom-decor real-room ${ui.lampOn===false?'lamp-off':''}">${background}${common}<button class="scene-object lamp-object" data-object="lamp" aria-label="Лампа"><span class="wall-lamp"><i></i></span></button><button class="scene-object bed-object" data-object="bed" aria-label="Кровать"><span class="bed"><i class="pillow"></i><i class="blanket"></i></span></button><div class="nightstand"></div></div>`;
 if(room==='bathroom')return `<div class="decor bathroom-decor real-room">${background}${common}<button class="scene-object tub-object" data-object="tub" aria-label="Ванна"><span class="tub"></span><span class="foam">○ ◌ ○</span></button><div class="shower"></div><div class="bath-shelf"></div></div>`;
 if(room==='toilet')return `<div class="decor toilet-decor real-room">${background}${common}<button class="scene-object litter-object" data-object="litter" aria-label="Лоток"><span class="litter-box"></span></button><div class="bath-shelf"></div></div>`;
 if(room==='wardrobe')return `<div class="decor wardrobe-decor real-room">${background}${common}<button class="scene-object closet-object" data-object="closet" aria-label="Гардероб"><span class="closet"></span></button><div class="mirror"></div></div>`;
 if(room==='playroom')return `<div class="decor playroom-decor real-room">${background}${common}<button class="scene-object toy-object" data-object="toy" aria-label="Игрушки"><span class="toy-box">🧶</span></button><div class="play-rug"></div><div class="cat-tree"></div></div>`;
 if(room==='lake')return `<div class="decor lake-decor real-room">${background}<div class="sky"></div><div class="hills"></div><button class="scene-object water-object" data-object="water" aria-label="Рыбачить"><span class="water"></span></button><div class="dock"></div></div>`;
 return `<div class="decor living-decor real-room"><img class="room-background" src="${HALL_BG}" alt="" draggable="false"><div class="room-vignette"></div><button class="scene-hotspot hall-toy-hotspot" data-object="toy" aria-label="Игрушки"></button><button class="scene-hotspot hall-kitchen-hotspot" data-room="kitchen" aria-label="Кухня"></button></div>`;
}