let ctx=null,master=null,timer=null,currentRoom=null;
const roomNotes={living:[261.63,329.63,392],kitchen:[293.66,369.99,440],bathroom:[220,277.18,329.63],toilet:[246.94,311.13,369.99],bedroom:[196,246.94,293.66],wardrobe:[277.18,349.23,415.3],playroom:[329.63,415.3,493.88],lake:[174.61,220,261.63]};
function ensure(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.16;master.connect(ctx.destination)}
function tone(freq,dur=.9,vol=.15,type='sine'){ensure();const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(vol,ctx.currentTime+.08);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g);g.connect(master);o.start();o.stop(ctx.currentTime+dur)}
export function startRoomMusic(room){ensure();if(ctx.state==='suspended')ctx.resume();if(currentRoom===room&&timer)return;currentRoom=room;clearInterval(timer);let i=0;const play=()=>{const notes=roomNotes[currentRoom]||roomNotes.living;tone(notes[i++%notes.length],1.7,.09,'sine')};play();timer=setInterval(play,1900)}
export function stopMusic(){clearInterval(timer);timer=null}
export function sfx(kind){const f={pet:520,feed:620,drink:720,bath:440,toilet:350,play:800,sleep:260}[kind]||500;tone(f,.28,.24,kind==='play'?'triangle':'sine')}
export function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.pitch=1.55;u.rate=.92;u.volume=.42;window.speechSynthesis.speak(u)}

export function purr(duration=2.8){ensure();if(ctx.state==='suspended')ctx.resume();const now=ctx.currentTime,end=now+duration;const carrier=ctx.createOscillator(),harm=ctx.createOscillator(),mod=ctx.createOscillator(),modGain=ctx.createGain(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();carrier.type='sine';carrier.frequency.value=26;harm.type='sine';harm.frequency.value=52;mod.type='sine';mod.frequency.value=22;modGain.gain.value=.055;filter.type='lowpass';filter.frequency.value=135;filter.Q.value=.7;gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(.34,now+.18);gain.gain.setValueAtTime(.30,end-.22);gain.gain.linearRampToValueAtTime(.001,end);mod.connect(modGain);modGain.connect(gain.gain);carrier.connect(filter);harm.connect(filter);filter.connect(gain);gain.connect(master);carrier.start(now);harm.start(now);mod.start(now);carrier.stop(end);harm.stop(end);mod.stop(end)}

function noise(duration=.8,vol=.07,filterFreq=1800){ensure();const len=Math.floor(ctx.sampleRate*duration),buf=ctx.createBuffer(1,len,ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buf;filter.type='lowpass';filter.frequency.value=filterFreq;g.gain.value=vol;src.connect(filter);filter.connect(g);g.connect(master);src.start()}
export function waterSound(){noise(2.2,.16,2600)}
export function fartSound(){ensure();if(ctx.state==='suspended')ctx.resume();tone(92,.16,.20,'sawtooth');setTimeout(()=>tone(64,.24,.16,'sawtooth'),105)}
export function flushSound(){noise(1.4,.22,1100);setTimeout(()=>tone(110,.7,.13,'sine'),250)}
export function applauseSound(){ensure();if(ctx.state==='suspended')ctx.resume();for(let i=0;i<9;i++)setTimeout(()=>noise(.12,.10,3200),i*105);setTimeout(()=>tone(659,.18,.14,'triangle'),160);setTimeout(()=>tone(784,.28,.16,'triangle'),360)}
export function eatSound(){for(let i=0;i<4;i++)setTimeout(()=>tone(180+i*22,.12,.12,'triangle'),i*180)}
export function meow(kind='want'){const map={food:[420,520],sleep:[350,300],toilet:[480,390],bath:[520,440],play:[620,760],fish:[560,690],want:[440,540]};const n=map[kind]||map.want;tone(n[0],.22,.2,'triangle');setTimeout(()=>tone(n[1],.3,.18,'triangle'),170)}

export function happyJingle(){ensure();if(ctx.state==='suspended')ctx.resume();[523,659,784,1047].forEach((f,i)=>setTimeout(()=>tone(f,.24,.12,'triangle'),i*115))}
export function sleepyChime(){ensure();if(ctx.state==='suspended')ctx.resume();[392,330,262].forEach((f,i)=>setTimeout(()=>tone(f,.5,.08,'sine'),i*260))}
