let ctx=null,timer=null,currentRoom=null;
let musicBus=null,sfxBus=null,voiceBus=null;
let settings={musicEnabled:true,sfxEnabled:true,voiceEnabled:true,musicVolume:.35,sfxVolume:.7,voiceVolume:.65};
const roomNotes={living:[261.63,329.63,392],kitchen:[293.66,369.99,440],bathroom:[220,277.18,329.63],toilet:[246.94,311.13,369.99],bedroom:[196,246.94,293.66],wardrobe:[277.18,349.23,415.3],playroom:[329.63,415.3,493.88],lake:[174.61,220,261.63],store:[349.23,440,523.25]};
function ensure(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();musicBus=ctx.createGain();sfxBus=ctx.createGain();voiceBus=ctx.createGain();musicBus.connect(ctx.destination);sfxBus.connect(ctx.destination);voiceBus.connect(ctx.destination);applyVolumes()}
function applyVolumes(){if(!ctx)return;musicBus.gain.setTargetAtTime((settings.musicEnabled===false?0:settings.musicVolume*.34),ctx.currentTime,.08);sfxBus.gain.setTargetAtTime((settings.sfxEnabled===false?0:settings.sfxVolume*.34),ctx.currentTime,.05);voiceBus.gain.setTargetAtTime((settings.voiceEnabled===false?0:settings.voiceVolume*.34),ctx.currentTime,.05)}
export function configureAudio(next={}){settings={...settings,...next};ensure();applyVolumes()}
function tone(freq,dur=.9,vol=.15,type='sine',bus='sfx'){ensure();const o=ctx.createOscillator(),g=ctx.createGain(),out=bus==='music'?musicBus:bus==='voice'?voiceBus:sfxBus;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.linearRampToValueAtTime(vol,ctx.currentTime+.06);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.connect(g);g.connect(out);o.start();o.stop(ctx.currentTime+dur)}
export function startRoomMusic(room){ensure();if(ctx.state==='suspended')ctx.resume();if(currentRoom===room&&timer)return;currentRoom=room;clearInterval(timer);let i=0;const play=()=>{const notes=roomNotes[currentRoom]||roomNotes.living;tone(notes[i++%notes.length],1.7,.09,'sine','music')};play();timer=setInterval(play,1900)}
export function stopMusic(){clearInterval(timer);timer=null;currentRoom=null}
export function duckMusic(on=true){ensure();musicBus.gain.setTargetAtTime((on?.10:(settings.musicEnabled===false?0:settings.musicVolume*.34)),ctx.currentTime,.12)}
export function sfx(kind){const f={pet:520,feed:620,drink:720,bath:440,toilet:350,play:800,sleep:260,step:330,jump:690,draw:570,cast:460,catch:880,miss:260,coin:980,level:1040}[kind]||500;tone(f,.28,.24,kind==='play'?'triangle':'sine')}
export function purr(duration=2.8){ensure();if(ctx.state==='suspended')ctx.resume();const now=ctx.currentTime,end=now+duration;const carrier=ctx.createOscillator(),harm=ctx.createOscillator(),mod=ctx.createOscillator(),modGain=ctx.createGain(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();carrier.type='sine';carrier.frequency.value=26;harm.type='sine';harm.frequency.value=52;mod.type='sine';mod.frequency.value=22;modGain.gain.value=.055;filter.type='lowpass';filter.frequency.value=135;gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(.34,now+.18);gain.gain.setValueAtTime(.30,end-.22);gain.gain.linearRampToValueAtTime(.001,end);mod.connect(modGain);modGain.connect(gain.gain);carrier.connect(filter);harm.connect(filter);filter.connect(gain);gain.connect(sfxBus);carrier.start(now);harm.start(now);mod.start(now);carrier.stop(end);harm.stop(end);mod.stop(end)}
function noise(duration=.8,vol=.07,filterFreq=1800){ensure();const len=Math.floor(ctx.sampleRate*duration),buf=ctx.createBuffer(1,len,ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buf;filter.type='lowpass';filter.frequency.value=filterFreq;g.gain.value=vol;src.connect(filter);filter.connect(g);g.connect(sfxBus);src.start()}
export function waterSound(){noise(2.2,.16,2600)}
export function fartSound(){tone(92,.16,.20,'sawtooth');setTimeout(()=>tone(64,.24,.16,'sawtooth'),105)}
export function flushSound(){noise(1.4,.22,1100);setTimeout(()=>tone(110,.7,.13),250)}
export function applauseSound(){for(let i=0;i<9;i++)setTimeout(()=>noise(.12,.10,3200),i*105)}
export function eatSound(){for(let i=0;i<4;i++)setTimeout(()=>tone(180+i*22,.12,.12,'triangle'),i*180)}
export function meow(kind='want'){const map={food:[420,520],sleep:[350,300],toilet:[480,390],bath:[520,440],play:[620,760],fish:[560,690],happy:[650,820],sad:[390,320],annoyed:[330,430],want:[440,540]};const n=map[kind]||map.want;tone(n[0],.22,.2,'triangle','voice');setTimeout(()=>tone(n[1],.3,.18,'triangle','voice'),170)}
export function happyJingle(){[523,659,784,1047].forEach((f,i)=>setTimeout(()=>tone(f,.24,.12,'triangle'),i*115))}
export function sleepyChime(){[392,330,262].forEach((f,i)=>setTimeout(()=>tone(f,.5,.08),i*260))}
