export const LEVELS=Array.from({length:100},(_,i)=>{const level=i+1;return{level,xp:Math.round(80+level*45+Math.pow(level,1.35)*18),coins:50+level*15,item:level%5===0?'gift_level_'+level:null}});
export const levelData=level=>LEVELS[Math.min(LEVELS.length-1,Math.max(0,level-1))];
export const quests=[
{id:'care3',name:'Забота',goal:3,reward:{coins:35,xp:15},type:'care'},{id:'play2',name:'Время игры',goal:2,reward:{coins:30,xp:15},type:'play'},{id:'fish1',name:'Первая рыбалка',goal:1,reward:{coins:45,xp:20},type:'fish'}
];
export const achievements=[
{id:'firstMeal',name:'Первый обед',reward:{coins:25,item:'gift_treat'}},{id:'firstBath',name:'Первое купание',reward:{coins:25}},{id:'firstToy',name:'Первая игра',reward:{coins:25}},{id:'firstFish',name:'Первая рыбка',reward:{coins:40,item:'gift_bait'}},{id:'firstOutfit',name:'Первый образ',reward:{coins:30}}
];
const dayKey=(d=new Date())=>d.toISOString().slice(0,10);
export function ensureProgress(s){const n=structuredClone(s);n.progress??={streak:0,lastDaily:null,actions:{care:0,play:0,fish:0},claimed:[],achievements:[],drawings:[],levelClaims:[],milestones:[]};for(const k of ['claimed','achievements','drawings','levelClaims','milestones'])n.progress[k]??=[];n.progress.actions??={care:0,play:0,fish:0};n.inventory.owned??=[];return n}
export function track(s,type,amount=1){const n=ensureProgress(s);n.progress.actions[type]=(n.progress.actions[type]||0)+amount;return n}
function grant(n,reward={}){n.economy.coins+=(reward.coins||0);n.economy.xp+=(reward.xp||0);if(reward.item&&!n.inventory.owned.includes(reward.item))n.inventory.owned.push(reward.item);return n}
export function processLevels(s){let n=ensureProgress(s),leveled=[];while(n.economy.level<100){const d=levelData(n.economy.level);if(n.economy.xp<d.xp)break;n.economy.xp-=d.xp;n.economy.level++;const claim='level_'+n.economy.level;if(!n.progress.levelClaims.includes(claim)){n.progress.levelClaims.push(claim);grant(n,{coins:d.coins,item:d.item});leveled.push({level:n.economy.level,coins:d.coins,item:d.item})}}return{state:n,leveled,next:levelData(n.economy.level)}}
export function dailyReward(s){const n=ensureProgress(s),today=dayKey();if(n.progress.lastDaily===today)return{state:n,ok:false};const yesterday=dayKey(new Date(Date.now()-86400000)),gap=n.progress.lastDaily?Math.floor((Date.parse(today)-Date.parse(n.progress.lastDaily))/86400000):0;n.progress.streak=n.progress.lastDaily===yesterday?n.progress.streak+1:gap<=2?Math.max(1,n.progress.streak):1;n.progress.lastDaily=today;const milestones={3:{coins:100,item:'gift_3day'},7:{coins:250,item:'gift_7day'},14:{coins:500,item:'gift_14day'},30:{coins:1200,item:'gift_30day'}};const reward={coins:40+Math.min(80,n.progress.streak*5)};const m=milestones[n.progress.streak];if(m&&!n.progress.milestones.includes('streak_'+n.progress.streak)){n.progress.milestones.push('streak_'+n.progress.streak);reward.coins+=m.coins;reward.item=m.item}grant(n,reward);return{state:n,ok:true,reward}}
export function claimQuest(s,id){const n=ensureProgress(s),q=quests.find(x=>x.id===id);if(!q||n.progress.claimed.includes(id)||(n.progress.actions[q.type]||0)<q.goal)return{state:n,ok:false};n.progress.claimed.push(id);grant(n,q.reward);return{state:n,ok:true,reward:q.reward}}
export function unlockAchievement(s,id){const n=ensureProgress(s),a=achievements.find(x=>x.id===id);if(!a||n.progress.achievements.includes(id))return{state:n,ok:false};n.progress.achievements.push(id);grant(n,a.reward);return{state:n,ok:true,reward:a.reward}}
export function addDrawing(s){const n=ensureProgress(s),item={id:'drawing_'+Date.now(),createdAt:Date.now()};n.progress.drawings.push(item);n.economy.xp+=7;return{state:n,item}}
