const make=(id,name,category,price,rarity='Common',level=1,effect=null,currency='coins',extra={})=>({id,name,image:null,category,price,currency,rarity,level,quantity:1,owned:false,isNew:true,destination:category,effect,...extra});
export const catalog=[
make('food_salmon','Лосось','food',20,'Common',1,{hunger:28}),make('food_tuna','Тунец','food',22,'Common',1,{hunger:28}),make('food_chicken','Курица','food',18),make('food_meat','Мясо','food',24),make('food_steak','Стейк','food',38,'Uncommon',3),make('food_sausage','Сосиски','food',16),make('food_cheese','Сыр','food',15),make('food_bread','Хлеб','food',10),make('food_pie','Пирожок','food',14),make('food_salad','Салат','food',18),make('food_pasta','Паста','food',24),make('food_seafood','Паста с морепродуктами','food',34,'Uncommon',2),make('food_soup','Суп','food',18),make('food_cutlet','Макароны с котлетой','food',28),make('food_mash','Пюре с курицей','food',26),
make('drink_water','Вода','drinks',8),make('drink_milk','Молоко','drinks',14),make('drink_berry','Ягодный напиток','drinks',18,'Uncommon',2),
make('treat_cookie','Печенье-лапка','treats',16),make('treat_cake','Торт','treats',45,'Rare',4),make('treat_icecream','Мороженое','treats',28,'Uncommon',2),make('treat_candy','Конфеты','treats',20),
...['Мячик','Мышка','Удочка с пером','Лазер','Клубок','Тоннель','Пружинка','Плюшевая рыбка'].map((n,i)=>make('toy_'+i,n,'toys',35+i*12,i>5?'Rare':'Common',1+Math.floor(i/3),{mood:15})),
...['Альбом','Краски','Кисти','Карандаши','Мелки','Фломастеры','Мольберт'].map((n,i)=>make('art_'+i,n,'art',25+i*10,i>4?'Uncommon':'Common',1,{draw:true})),
...['Пижама звёзды','Свитер лавандовый','Худи','Платье','Стильный костюм','Карнавальный костюм'].map((n,i)=>make('outfit_'+i,n,i===0?'pajamas':i===5?'costumes':'outfits',70+i*25,i>3?'Rare':'Common',1+Math.floor(i/2),null,'coins',{slot:'body'})),
...['Шляпка','Корона'].map((n,i)=>make('hat_'+i,n,'hats',90+i*55,i?'Epic':'Rare',3+i,null,'coins',{slot:'head'})),
make('glasses_round','Круглые очки','glasses',95,'Rare',3,null,'coins',{slot:'eyes'}),make('collar_moon','Лунный ошейник','collars',80,'Uncommon',2,null,'coins',{slot:'neck'}),make('shoes_purple','Лиловые ботиночки','shoes',120,'Rare',4,null,'coins',{slot:'feet'}),make('bag_small','Рюкзачок','accessories',105,'Rare',3,null,'coins',{slot:'accessory'}),
make('bath_towel','Мягкое полотенце','bath',55),make('bath_dryer','Фен','bath',90,'Uncommon',2),
...['Диван','Кресло','Пуф','Ковёр','Столик','Лампа-звезда','Растение','Полка','Аквариум','Кошачье дерево'].map((n,i)=>make('furn_'+i,n,'furniture',90+i*28,i>7?'Rare':'Common',1+Math.floor(i/3),{decorate:true})),
make('bed_cloud','Кровать-облако','beds',180,'Rare',4,{decorate:true}),make('kitchen_bowl','Лиловая миска','kitchen',80,'Uncommon',2,{decorate:true}),make('decor_picture','Картина','decor',95,'Uncommon',2,{decorate:true}),
make('rod_bamboo','Удочка бамбуковая','rods',75),make('rod_lake','Удочка озёрная','rods',150,'Rare',4),make('tackle_box','Коробка снастей','fishing',90),make('fish_bucket','Ведро','fishing',55),make('bait_worm','Наживка','fishing',18),
make('season_scarf','Зимний шарф','seasonal',160,'Epic',7,null,'coins',{slot:'neck'}),make('rare_crown','Лунная корона','rare',450,'Legendary',12,null,'coins',{slot:'head'}),make('gift_box','Подарочная коробка','gifts',100,'Rare',5),
make('premium_starlight','Звёздный ошейник','premium',49,'Legendary',1,null,'XTR',{stars:49,slot:'neck'})
];
export const categories=[...new Set(catalog.map(x=>x.category))];
const wearable=i=>['pajamas','outfits','costumes','hats','glasses','accessories','shoes','collars','seasonal','rare','premium'].includes(i.category);
export function buyItem(state,id){const n=structuredClone(state),item=catalog.find(x=>x.id===id);if(!item)return{state:n,ok:false,reason:'missing'};if(item.currency==='XTR')return{state:n,ok:false,reason:'premium'};n.inventory.owned??=[];const stackable=['food','drinks','treats','fishing'].includes(item.category);if(n.inventory.owned.includes(id)&&!stackable)return{state:n,ok:false,reason:'owned'};if(n.economy.level<item.level)return{state:n,ok:false,reason:'level'};if(n.economy.coins<item.price)return{state:n,ok:false,reason:'coins'};n.economy.coins-=item.price;if(stackable){n.inventory.food[id]=(n.inventory.food[id]||0)+1}else{n.inventory.owned.push(id);if(wearable(item))n.inventory.clothes.push(id);if(['furniture','beds','kitchen','decor'].includes(item.category))n.inventory.furniture.push(id)}n.economy.xp+=4;n.activity={type:'celebrate',stage:'jump',itemId:id,startedAt:Date.now()};n.needs.mood=Math.min(100,n.needs.mood+5);return{state:n,ok:true,item}}
export function equipItem(state,id){const n=structuredClone(state),item=catalog.find(x=>x.id===id);if(!item||!n.inventory.clothes.includes(id))return n;n.inventory.equipped??={};n.inventory.equipped[item.slot||'body']=id;return n}
export function applyFurniture(state,id,room=state.room){const n=structuredClone(state);if(!n.inventory.furniture?.includes(id))return n;n.roomDecor??={};n.roomDecor[room]??=[];if(!n.roomDecor[room].includes(id))n.roomDecor[room].push(id);return n}
export function ownedInteractive(state,category){return catalog.filter(x=>x.category===category&&state.inventory.owned?.includes(x.id))}
