export const catalog=[
...['Бантик лиловый','Бантик розовый','Бантик мятный','Ошейник лунный','Ошейник жемчужный','Шарфик','Свитер кремовый','Свитер лавандовый','Худи','Пижама звёзды','Дождевик','Комбинезон','Платье','Жилет','Шляпка','Корона','Очки круглые','Рюкзачок'].map((name,i)=>({id:'wear_'+i,category:'clothes',name,price:60+i*18,rarity:i>13?'rare':'common',level:1+Math.floor(i/6),slot:i<6?'neck':i<14?'body':'head'})),
...['Лосось','Тунец','Курица','Индейка','Креветки','Сардины','Паштет','Суп','Рыбные кусочки','Молоко','Вода','Козье молоко','Ягодный напиток','Печенье-лапка','Торт ко дню рождения','Мороженое для котят'].map((name,i)=>({id:'food_'+i,category:'food',name,price:12+i*4,rarity:i>12?'rare':'common',level:1})),
...['Мячик','Мышка','Удочка с пером','Лазер','Клубок','Тоннель','Пружинка','Погремушка','Когтеточка','Плюшевая рыбка','Интерактивный шар','Коробка','Мыльные пузыри'].map((name,i)=>({id:'toy_'+i,category:'toys',name,price:45+i*12,rarity:i>9?'rare':'common',level:1+Math.floor(i/5),action:'play'})),
...['Кровать-облако','Домик','Диван','Кресло','Пуф','Ковёр','Столик','Лампа-звезда','Торшер','Растение','Полка','Подушка','Плед','Шторы','Картина','Аквариум','Кошачье дерево','Когтеточка-башня'].map((name,i)=>({id:'furn_'+i,category:'furniture',name,price:90+i*25,rarity:i>13?'rare':'common',level:1+Math.floor(i/5)})),
...['Удочка бамбуковая','Удочка озёрная','Удочка серебряная','Катушка','Леска прочная','Крючки','Поплавок','Сачок','Ведро','Коробка снастей','Черви','Блёсны','Приманка рыбка'].map((name,i)=>({id:'fish_'+i,category:'fishing',name,price:35+i*20,rarity:i>8?'rare':'common',level:1+Math.floor(i/4),action:'fish'})),
...['Альбом','Краски','Кисти','Карандаши','Мелки','Фломастеры','Наклейки','Мольберт','Палитра'].map((name,i)=>({id:'art_'+i,category:'art',name,price:30+i*14,rarity:i>6?'rare':'common',level:1,action:'draw'}))
];
export const categories=['clothes','food','toys','furniture','fishing','art'];
export function buyItem(state,id){const n=structuredClone(state),item=catalog.find(x=>x.id===id);if(!item)return{state:n,ok:false,reason:'missing'};n.inventory.owned??=[];if(n.inventory.owned.includes(id)&&item.category!=='food')return{state:n,ok:false,reason:'owned'};if(n.economy.level<item.level)return{state:n,ok:false,reason:'level'};if(n.economy.coins<item.price)return{state:n,ok:false,reason:'coins'};n.economy.coins-=item.price;if(item.category==='food'){n.inventory.food[id]=(n.inventory.food[id]||0)+1}else{n.inventory.owned.push(id);if(item.category==='clothes')n.inventory.clothes.push(id);if(item.category==='furniture')n.inventory.furniture.push(id)}n.economy.xp+=4;return{state:n,ok:true,item}}
export function equipItem(state,id){const n=structuredClone(state),item=catalog.find(x=>x.id===id);if(!item||!n.inventory.clothes.includes(id))return n;n.inventory.equipped??={};if(typeof n.inventory.equipped!=='object')n.inventory.equipped={};n.inventory.equipped[item.slot||'body']=id;return n}
export function ownedInteractive(state,category){return catalog.filter(x=>x.category===category&&state.inventory.owned?.includes(x.id))}