import { renderWelcome,renderGame } from './ui/appView.js';
import { createInitialState,restoreState,tickState,petKitten,feedKitten,setSleeping,drink,bathe,useToilet,play,getWant,wantSpeech,toggleLamp,rewardPetting } from './core/state.js';
import { saveGame } from './core/persistence.js';import { t } from './data/localization.js';
import { startRoomMusic,stopMusic,sfx,speak,purr,waterSound,flushSound,eatSound,meow } from './core/audio.js';
const app=document.querySelector('#app');let state=restoreState(),bubble='',bubbleTimer=null,actionLock=false,soundOn=false,lastWant=null,lastWantAt=0,ui={fridgeOpen:false};
const lang=()=>state?.settings?.language||'ru';
function showBubble(text,ms=1500){bubble=text;clearTimeout(bubbleTimer);render();bubbleTimer=setTimeout(()=>{bubble='';render()},ms)}
function persist(){if(!state)return;state.lastSeenAt=Date.now();saveGame(state)}
function render(){if(!state){app.innerHTML=renderWelcome('ru');bindWelcome();return}app.innerHTML=renderGame(state,bubble,ui);bindGame()}
function bindWelcome(){const input=document.querySelector('#pet-name'),start=document.querySelector('#start-game');input.addEventListener('input',()=>start.disabled=!input.value.trim());start.addEventListener('click',()=>{const name=input.value.trim();if(!name)return;state=createInitialState(name,'ru');persist();render();setTimeout(()=>showBubble('Мяу! ♥'),250)})}
function doAction(fn,msg,kind='pet'){if(actionLock)return;actionLock=true;state=fn(state);persist();sfx(kind);if(kind==='pet'||kind==='play')speak(msg);showBubble(msg);setTimeout(()=>actionLock=false,500)}
function petDirect(){if(state.sleeping||actionLock)return;soundOn=true;startRoomMusic(state.room);purr(2.8);const r=rewardPetting(state);state=r.state;state.activity={type:'petted',stage:'happy',startedAt:Date.now()};persist();showBubble(r.rewarded?'Хр-р-р-р-р… ♥ +2 XP':'Хр-р-р-р-р… ♥',1200)}
function bindGame(){const pet=document.querySelector('.pet-button');let petStart=null,petMoved=false;pet?.addEventListener('pointerdown',e=>{petStart={x:e.clientX,y:e.clientY};petMoved=false;pet.classList.add('is-stroking');pet.setPointerCapture?.(e.pointerId)});pet?.addEventListener('pointermove',e=>{if(!petStart)return;const d=Math.hypot(e.clientX-petStart.x,e.clientY-petStart.y);if(d>10){petMoved=true;pet.style.setProperty('--stroke-x',Math.max(-10,Math.min(10,(e.clientX-petStart.x)/5))+'px')}});pet?.addEventListener('pointerup',e=>{if(!petStart)return;const d=Math.hypot(e.clientX-petStart.x,e.clientY-petStart.y);petStart=null;pet.classList.remove('is-stroking');pet.style.removeProperty('--stroke-x');if(petMoved||d>12)petDirect()});pet?.addEventListener('pointercancel',()=>{petStart=null;petMoved=false;pet.classList.remove('is-stroking');pet.style.removeProperty('--stroke-x')});const toggleFridge=()=>{ui.fridgeOpen=!ui.fridgeOpen;render();if(ui.fridgeOpen)showBubble('Выбирай еду ♥',900)};document.querySelector('[data-object="fridge"]')?.addEventListener('click',toggleFridge);document.querySelector('[data-action="open-fridge"]')?.addEventListener('click',()=>{if(state.room!=='kitchen'){state.room='kitchen';ui.fridgeOpen=true;persist();render();startRoomMusic('kitchen')}else toggleFridge()});document.querySelector('[data-object="lamp"]')?.addEventListener('click',()=>{state=toggleLamp(state);persist();render()});document.querySelector('[data-object="bed"]')?.addEventListener('click',()=>{state=setSleeping(state,!state.sleeping);persist();showBubble(state.sleeping?t('goodNight',lang()):'Доброе утро!')});document.querySelector('[data-object="tub"]')?.addEventListener('click',()=>{waterSound();doAction(bathe,'Чисто и пушисто!','bath')});document.querySelector('[data-object="litter"]')?.addEventListener('click',()=>{flushSound();doAction(useToilet,'Готово!','toilet')});document.querySelector('[data-object="toy"]')?.addEventListener('click',()=>doAction(play,'Ещё!','play'));document.querySelector('[data-object="water"]')?.addEventListener('click',()=>{state.activity={type:'fish',stage:'casting',startedAt:Date.now()};persist();sfx('play');showBubble('Забрасываю удочку…')});document.querySelectorAll('[data-room]').forEach(b=>b.addEventListener('click',()=>{if(actionLock)return;state.room=b.dataset.room;ui.fridgeOpen=false;soundOn=true;persist();render();startRoomMusic(state.room)}));
document.querySelectorAll('[data-action="pet"]').forEach(el=>el.addEventListener('click',petDirect));
document.querySelectorAll('[data-action="feed"]').forEach(el=>el.addEventListener('click',(event)=>{if(actionLock)return;actionLock=true;const btn=event.currentTarget;const r=feedKitten(state,btn.dataset.food||'dryFood');state=r.state;if(r.ok){ui.fridgeOpen=false;state.activity={type:'eating',stage:'chewing',startedAt:Date.now()};eatSound()}persist();showBubble(r.ok?t('yum',lang()):t('alreadyFull',lang()));setTimeout(()=>{state.activity={type:'idle',stage:'idle',startedAt:Date.now()};persist();render();actionLock=false},1500)}));
document.querySelector('[data-action="drink"]')?.addEventListener('click',()=>{if((state.inventory.food?.milk||0)>0){state.inventory.food.milk--;state=drink(state);persist();eatSound();showBubble('Ммм… молочко! ♥',1400)}else showBubble('Молоко закончилось',1400)});
document.querySelector('[data-action="bathe"]')?.addEventListener('click',()=>{waterSound();doAction(bathe,'Чисто и пушисто!','bath')});
document.querySelector('[data-action="toilet"]')?.addEventListener('click',()=>{flushSound();doAction(useToilet,'Готово!','toilet')});
document.querySelector('[data-action="play"]')?.addEventListener('click',()=>doAction(play,'Ещё!','play'));document.querySelector('[data-action="draw"]')?.addEventListener('click',()=>{state.activity={type:'draw',stage:'drawing',startedAt:Date.now()};persist();sfx('play');showBubble('Рисую!')});document.querySelector('[data-action="fish"]')?.addEventListener('click',()=>{state.activity={type:'fish',stage:'casting',startedAt:Date.now()};persist();sfx('play');showBubble('Забрасываю удочку…')});
document.querySelector('[data-action="shop"]')?.addEventListener('click',()=>showBubble('Магазин будет следующим разделом — пока используй стартовую еду',2200));document.querySelector('[data-action="settings"]')?.addEventListener('click',()=>showBubble('Настройки: музыка, звук и язык — раздел в разработке',2200));
document.querySelector('[data-action="sound"]')?.addEventListener('click',()=>{soundOn=!soundOn;if(soundOn){startRoomMusic(state.room);showBubble('Музыка включена')}else{stopMusic();showBubble('Музыка выключена')}});
document.querySelector('[data-action="sleep"]')?.addEventListener('click',()=>{if(actionLock)return;state=setSleeping(state,!state.sleeping);persist();showBubble(state.sleeping?t('goodNight',lang()):'Доброе утро!')})}
setInterval(()=>{if(state){state=tickState(state,10);const want=getWant(state),now=Date.now();if(want&&(want!==lastWant||now-lastWantAt>90000)){lastWant=want;lastWantAt=now;meow(want);speak(wantSpeech[want]);showBubble(wantSpeech[want],2400)}persist();render()}},10000);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist()});window.addEventListener('pagehide',persist);render();